### ISSUE TITLE
Dependency "cordova-plugin-add-swift-support" needs an update

### ISSUE THREAD

**Issue by fwolle30** [emcniece/cordova-plugin-wifiinfo#5]
If I try to build with cordova 8.1.2, I get the following error:

> `cordova build android`
> Android Studio project detected
> Cannot find module '../cordova/platform_metadata'
>

However, If I update the cordova-plugin-add-swift-support plugin to 1.7.2, everything builds as it should.
